### ISSUE TITLE
Is there a verto-min.js version controlled repository or npm repository ?

### ISSUE THREAD

**Issue by Leonewu** [freeswitch/verto-client#1]
hello, i am using verto-min.js to build a web outbound app. Recently I encountered some problem in that app. Is there a verto-min.js version controlled repository or some place I can checkout the change log of verto-min.js?

**Comment by victor-shelepen** [comment]
Should I use jsSIP, SIP.js instead? What is a status of the project?

**Comment by avimar** [comment]
What is the un-minified verto.js? There's 4 .js files inside the /js/ folder - is it just all of them together?

**Comment by seven1240** [comment]
js/src has all source code, and the min.js was generated on make
