### ISSUE TITLE
Building verto communicator with bower install fails

### ISSUE THREAD

**Issue by muteesa** [freeswitch/verto-client#3]
Bower install fails because the repository for Material design for bootstrap moved. 
hence I had to update that package to make it work. 

Error:  
bower bootstrap-material-design#~0.3.0         ENORESTARGET No tag found that was able to satisfy ~0.3.0

issue:

https://github.com/FezVrasta/bootstrap-material-design  changed to https://github.com/mdbootstrap/bootstrap-material-design

Solution:

I used https://libraries.io/bower/MDBootstrap which installed the design packages for me.
bower install MDBootstrap or edit bower.json and replace bootstrap-material-design#~0.3.0 with  "MDBootstrap":"~4.1.3",

regards,
Fred

**Comment by efficacy38** [comment]
I finded that we should edit something about bower.json

change the repo from bower to github's archive
"bootstrap-material-design": "git://github.com/mdbootstrap/bootstrap-material-design#~0.3.0"
