### ISSUE TITLE
Verto Ping

### ISSUE THREAD

**Issue by nblasgen** [freeswitch/verto-client#7]
https://github.com/freeswitch/verto-client/commit/54feff1ba1dadddaa6447babfdb888471c8362bd

In the above commit, the project's JQuery code was updated to handle a PING issue, but the actual Verto library was not updated to handle the ping.  Can we get this added to `verto-min.js` too?

**Comment by seven1240** [comment]
can you try the latest master? the verto-min.js was regenerated.
