### ISSUE TITLE
verot-client does not work in safari

### ISSUE THREAD

**Issue by looreypun** [freeswitch/verto-client#8]
When calling from verto-client, call does not connect after streaming is  success.
It work's fine in chrome and firefox.
offer SDP is not generated after stream success log.
Screenshot of console
![Screen Shot 2022-01-14 at 13 07 57](https://user-images.githubusercontent.com/45704147/149449942-c6fc00de-6f09-4adf-a3a3-5327b6fde22a.png)

**Comment by seven1240** [comment]
patch is welcome.

https://www.npmjs.com/package/@xswitch/rtc?activeTab=versions is a successor which is compatible and has some improvements.
